### ISSUE TITLE
Bug in Polygon/Polyline creation with multiple parts

### ISSUE THREAD

**Issue by L6SmxP5** [phpmyadmin/shapefile#12]
_savePolyLineRecord() in src/ShapeRecord.php does not work for geometries that have more than one part to them. Please refer to [page 14 of the Shapefile specification](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf#14) for details and an illustration of how the Parts field should be written. I've forked and fixed - 6492274.

**Comment by nijel** [comment]
Thanks, I've merged your changes (https://github.com/phpmyadmin/shapefile/pull/13).

**Comment by nijel** [comment]
I've just released 0.11 with this fix (and some other as well).

**Comment by L6SmxP5** [comment]
No problem nijel, I'm happy to have helped! I've also enhanced the library to write a .prj file specifying SRID. I'll commit for all to review soon.

**Comment by nijel** [comment]
Pull requests are always welcome :-).
